import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import SessionProviderWrapper from "./components/auth/SessionProviderWrapper";
import Link from "next/link";
import NavBar from "./components/auth/NavBar";

export const metadata: Metadata = {
  title: "Big Change",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <SessionProviderWrapper>
          <NavBar />
          <main className="container  py-12">{children}</main>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
